[package]
name = "fil_actor_market_state_v8"
description = "Builtin market actor for Filecoin"
version = "8.0.0"
license = "MIT OR Apache-2.0"
authors = [
    "ChainSafe Systems <info@chainsafe.io>",
    "Protocol Labs",
    "Filecoin Core Devs",
]
edition = "2018"
repository = "https://github.com/filecoin-project/builtin-actors"
keywords = ["filecoin", "web3", "wasm"]

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
fil_actors_runtime_common = { version = "9.0.0", path = "../../runtime", features = [
    "fil-actor",
] }
fvm_ipld_hamt = "0.5.1"
fvm_shared = { version = "2", default-features = false }
fvm_ipld_bitfield = "0.5.2"
num-traits = "0.2.14"
num-derive = "0.3.3"
serde = { version = "1.0.136", features = ["derive"] }
cid = { version = "0.8.3", default-features = false, features = [
    "serde-codec",
] }
log = "0.4.14"
anyhow = "1.0.56"
fvm_ipld_blockstore = "0.1.1"
fvm_ipld_encoding = "0.2.2"
libipld-core = { version = "0.13.1", features = ["serde-codec"] }

[dev-dependencies]
fil_actors_runtime_common = { version = "9.0.0", path = "../../runtime", features = [
    "test_utils",
    "sector-default",
] }
fil_actor_power_state_v8 = { version = "8.0.0", path = "../power_state_v8" }
fil_actor_reward_state_v8 = { version = "8.0.0", path = "../reward_state_v8" }
fil_actor_verifreg_state_v8 = { version = "8.0.0", path = "../verifreg_state_v8" }
fvm_ipld_amt = { version = "0.4.2", features = ["go-interop"] }
multihash = { version = "0.16.1", default-features = false }
regex = "1"
itertools = "0.10"

[features]
fil-actor = []
